//! Code generator - Translates the HIR to bytecode
//!
//! This module implements the code generation phase of the compiler: it
//! walks the HIR (`src/ir/hir.zig`, lowered from the parser's AST by
//! `src/frontend/lower/lower.zig`) and emits the backtracker's bytecode. Since F2c it
//! reads only the HIR; the bytecode is the same as the AST-based generator
//! produced (tests/snapshots/bytecode.txt).

const std = @import("std");
const Allocator = std.mem.Allocator;
const hir = @import("ir").hir;
const bytecode = @import("../bytecode/writer.zig");
const opcodes = @import("../bytecode/opcodes.zig");
const bittable_mod = @import("utils").bittable;
const BitTable = bittable_mod.BitTable;
const casefold = @import("unicode").casefold;
const charset_mod = @import("ir").charset;
const CharSet = charset_mod.CharSet;
const Range = charset_mod.Range;

const Node = hir.Node;
const BytecodeWriter = bytecode.BytecodeWriter;
const Label = bytecode.Label;
const Opcode = opcodes.Opcode;

/// Code generation error
pub const CodegenError = error{
    UnsupportedNode,
    InvalidPattern,
    TooManyGroups,
    OutOfMemory,
    // BytecodeWriter errors
    BufferTooSmall,
    UnknownOpcode,
    /// The unrolled program would exceed MAX_PROGRAM_BYTES (nested counted
    /// repeats multiply: `(?:a{65536}){65536}` is 2^32 copies).
    PatternTooLarge,
};

/// Cap on the generated bytecode: a program larger than this is
/// `error.PatternTooLarge` (docs/KNOWN_LIMITATIONS.md). Counted repeats are
/// unrolled (one copy of the atom per required repetition), so nested counts
/// multiply; without a cap `(?:a{65536}){65536}` built bytecode past 2 GiB
/// and panicked on an i32 jump offset (found by the F1c fuzz run).
///
/// 16 MiB is a measured choice, not the i32 limit (128x below it): the
/// largest single-atom counted repeat, `a{65536}` (MAX_REPEAT_UNROLL copies),
/// is 320 KiB, so the cap holds 51 of them; compiling a program at the cap
/// takes ~124 ms in ReleaseSafe (~400 ms in Debug). Counted loops that
/// remove the unrolling are F5's (D10).
pub const MAX_PROGRAM_BYTES: usize = 16 << 20;

/// Content-interning key of the CharSet table: the encoding hint's tag and
/// the table's ranges (borrowed from the table entry itself). Two classes
/// share an entry only when both agree.
const CharSetKey = struct {
    hint: std.meta.Tag(hir.EncodingHint),
    ranges: []const Range,
};

const CharSetKeyContext = struct {
    pub fn hash(_: CharSetKeyContext, key: CharSetKey) u64 {
        var h = std.hash.Wyhash.init(@intFromEnum(key.hint));
        h.update(std.mem.sliceAsBytes(key.ranges));
        return h.final();
    }
    pub fn eql(_: CharSetKeyContext, a: CharSetKey, b: CharSetKey) bool {
        return a.hint == b.hint and std.mem.eql(u8, std.mem.sliceAsBytes(a.ranges), std.mem.sliceAsBytes(b.ranges));
    }
};

/// Code generator for translating the HIR to bytecode
pub const CodeGenerator = struct {
    allocator: Allocator,
    writer: *BytecodeWriter,
    /// The flags of the enclosing ModifierScope (F2c: only the root one,
    /// so a single value saved and restored around the scope is enough;
    /// F5's modifiers nest scopes the same way).
    flags: hir.Flags = .{},
    /// The program's CharSet table (F2b), referenced by CHAR_SET idx.
    /// Indices are assigned in order of first appearance in the HIR walk,
    /// so the same pattern always yields the same bytecode and table.
    charsets: std.ArrayListUnmanaged(CharSet) = .empty,
    /// Bytes of `charsets` (8 per range), counted with the bytecode against
    /// MAX_PROGRAM_BYTES.
    charset_bytes: usize = 0,
    /// Content interning by (encoding hint, table ranges). Only a lookup;
    /// it never decides an index. Keys borrow the table entries' memory.
    charset_index: std.HashMapUnmanaged(CharSetKey, u32, CharSetKeyContext, std.hash_map.default_max_load_percentage) = .empty,
    /// CharSet node -> index, so an unrolled counted repeat (which generates
    /// the same node once per copy) builds its table entry only once.
    node_charset: std.AutoHashMapUnmanaged(*const Node, u32) = .empty,
    /// CharSet node -> its CHAR_CLASS bits, for the same reason.
    node_bitmap: std.AutoHashMapUnmanaged(*const Node, [32]u8) = .empty,

    const Self = @This();

    /// Maximum ASCII character value
    const MAX_ASCII = 127;

    /// Difference between uppercase and lowercase ASCII letters
    const CASE_DIFF = 32;

    /// Initialize a new code generator
    pub fn init(allocator: Allocator, writer: *BytecodeWriter) Self {
        return .{ .allocator = allocator, .writer = writer };
    }

    /// Free the CharSet table unless `takeCharSets` already took it.
    pub fn deinit(self: *Self) void {
        for (self.charsets.items) |cs| cs.deinit(self.allocator);
        self.charsets.deinit(self.allocator);
        self.charset_index.deinit(self.allocator);
        self.node_charset.deinit(self.allocator);
        self.node_bitmap.deinit(self.allocator);
    }

    /// Hand the CharSet table over to the caller (`CompileResult.charsets`);
    /// free each set, then the slice, with the generator's allocator.
    pub fn takeCharSets(self: *Self) Allocator.Error![]const CharSet {
        self.charset_index.clearAndFree(self.allocator);
        self.node_charset.clearAndFree(self.allocator);
        self.node_bitmap.clearAndFree(self.allocator);
        self.charset_bytes = 0;
        return self.charsets.toOwnedSlice(self.allocator);
    }

    /// Bytecode plus CharSet table: what MAX_PROGRAM_BYTES caps.
    fn programBytes(self: *const Self) usize {
        return self.writer.offset() + self.charset_bytes;
    }

    /// Generate bytecode from a HIR tree (its root is a ModifierScope).
    pub fn generate(self: *Self, root: *const Node) CodegenError!void {
        try self.generateNode(root);
        // Emit MATCH at the end to signal successful match
        try self.writer.emitSimple(.MATCH);
        // The per-node check in generateNode can let the last node run past
        // the cap; this makes the limit exact.
        if (self.programBytes() > MAX_PROGRAM_BYTES) return error.PatternTooLarge;
    }

    /// Generate code for a node. Only dispatches: the kinds that nest stay
    /// on the recursive path, the leaves go to the `noinline`
    /// `generateLeaf` so a nesting level's frame stays small (F2a's rule).
    fn generateNode(self: *Self, node: *const Node) CodegenError!void {
        if (self.programBytes() > MAX_PROGRAM_BYTES) return error.PatternTooLarge;
        switch (node.*) {
            .seq => |items| for (items) |item| try self.generateNode(item),
            .alt => |items| try self.generateAlternation(items),
            .repeat => |r| try self.generateRepeat(r),
            .capture => |c| try self.generateGroup(c),
            .look => |l| try self.generateLook(l),
            .modifier_scope => |m| {
                const saved = self.flags;
                self.flags = m.flags;
                defer self.flags = saved;
                try self.generateNode(m.body);
            },
            .empty, .literal, .char_set, .backref, .assert => try self.generateLeaf(node),
        }
    }

    noinline fn generateLeaf(self: *Self, node: *const Node) CodegenError!void {
        switch (node.*) {
            .empty => {},
            .literal => |lit| for (lit.units) |unit| try self.generateUnit(unit),
            .char_set => |cs| try self.generateCharSet(node, cs),
            .backref => |b| try self.generateBackRef(b),
            .assert => |a| try self.generateAssert(a),
            else => unreachable,
        }
    }

    // =========================================================================
    // Character Matching
    // =========================================================================

    /// Generate one literal unit, exactly as the AST generator did (see
    /// `hir.Literal`: one CHAR32 per byte-level unit, never merged). A code
    /// point <= U+007F or a raw byte is one CHAR32 (both ASCII cases under
    /// `i`); a code point above U+007F is its WTF-8 bytes, with its simple
    /// case-fold pair as an alternative under `i`.
    noinline fn generateUnit(self: *Self, unit: hir.LitUnit) !void {
        if (unit.raw_byte or unit.value <= MAX_ASCII) return self.generateChar(unit.value);

        var bytes_buf: [4]u8 = undefined;
        const len = std.unicode.wtf8Encode(@intCast(unit.value), &bytes_buf) catch return error.InvalidPattern;
        const bytes = bytes_buf[0..len];

        if (self.flags.ignore_case) {
            const opposite = casefold.toUpper(unit.value) orelse casefold.toLower(unit.value);
            if (opposite) |opp| {
                var buf: [4]u8 = undefined;
                const opp_len = std.unicode.utf8Encode(@intCast(opp), &buf) catch unreachable;

                var orig_label = try self.writer.createLabel();
                var opp_label = try self.writer.createLabel();
                var after_label = try self.writer.createLabel();

                try self.writer.emitSplit(.SPLIT, orig_label, opp_label);
                try self.writer.defineLabel(&orig_label);
                for (bytes) |b| try self.generateChar(b);
                try self.writer.emitJump(.GOTO, after_label);
                try self.writer.defineLabel(&opp_label);
                for (buf[0..opp_len]) |b| {
                    try self.writer.emit1(.CHAR32, b);
                }
                try self.writer.defineLabel(&after_label);
                return;
            }
        }

        for (bytes) |b| try self.generateChar(b);
    }

    /// Generate code for one CHAR32 unit (a code point <= U+007F, or a byte)
    fn generateChar(self: *Self, char: u32) !void {
        // If case-insensitive mode and this is an ASCII letter, generate alternation
        if (self.flags.ignore_case and char <= MAX_ASCII) {
            const c = @as(u8, @intCast(char));

            // Check if it's a letter
            const is_lower = c >= 'a' and c <= 'z';
            const is_upper = c >= 'A' and c <= 'Z';

            if (is_lower or is_upper) {
                // Generate alternation: lowercase|uppercase
                const lower = if (is_lower) c else c + CASE_DIFF;
                const upper = if (is_upper) c else c - CASE_DIFF;

                // Generate alternation: SPLIT upper_label, lower_label;
                // lower_label: lower; GOTO after; upper_label: upper; after:
                var lower_label = try self.writer.createLabel();
                var upper_label = try self.writer.createLabel();
                var after_label = try self.writer.createLabel();

                try self.writer.emitSplit(.SPLIT, upper_label, lower_label);
                try self.writer.defineLabel(&lower_label);
                try self.writer.emit1(.CHAR32, lower);
                try self.writer.emitJump(.GOTO, after_label);
                try self.writer.defineLabel(&upper_label);
                try self.writer.emit1(.CHAR32, upper);
                try self.writer.defineLabel(&after_label);

                return;
            }
        }

        // Normal case: just emit the character
        try self.writer.emit1(.CHAR32, char);
    }

    /// Generate a CharSet node in the encoding its `encoding_hint` names.
    /// What matches is `cs.set` whatever the encoding; the `_INV` opcodes
    /// take the members, `complement(set)` (exact, so tables and bitmaps
    /// are the same as before F2c).
    noinline fn generateCharSet(self: *Self, node: *const Node, cs: hir.CharSetNode) !void {
        switch (cs.encoding_hint) {
            .dot => |d| try self.writer.emitSimple(if (d.dot_all) .CHAR_ANY else .CHAR),
            .property => |p| {
                const opcode: Opcode = switch (p.kind) {
                    .general_category => if (cs.inverted) .UNICODE_PROPERTY_INV else .UNICODE_PROPERTY,
                    .script => if (cs.inverted) .UNICODE_SCRIPT_INV else .UNICODE_SCRIPT,
                    .script_extensions => if (cs.inverted) .UNICODE_SCRIPT_EXTENSIONS_INV else .UNICODE_SCRIPT_EXTENSIONS,
                };
                try self.writer.emit1(opcode, p.value);
            },
            // Under `i` an ASCII byte range needs both cases of its letters,
            // which CHAR_RANGE can't express: a bitmap instead.
            .byte_range => |r| if (self.flags.ignore_case and r.hi <= MAX_ASCII)
                try self.emitBitmap(node, cs)
            else
                try self.writer.emit2(if (cs.inverted) .CHAR_RANGE_INV else .CHAR_RANGE, r.lo, r.hi),
            .bitmap => try self.emitBitmap(node, cs),
            .set => {
                const idx = try self.charSetIndex(node, cs);
                try self.writer.emit1(if (cs.inverted) .CHAR_SET_INV else .CHAR_SET, idx);
            },
        }
    }

    /// CHAR_CLASS(_INV) with the members' bits. The members (`set`, or its
    /// complement for `_INV`) are all ASCII on this path, so bit `c` is just
    /// membership of `c` for c in 0..255 -- no allocation, which matters
    /// because an unrolled repeat (`[^a]{65536}`) emits the same class once
    /// per copy.
    fn emitBitmap(self: *Self, node: *const Node, cs: hir.CharSetNode) !void {
        const opcode: Opcode = if (cs.inverted) .CHAR_CLASS_INV else .CHAR_CLASS;
        if (self.node_bitmap.getPtr(node)) |bits| return self.writer.emitCharClass(opcode, bits);
        var table = BitTable.init();
        for (0..256) |c| {
            const in_set = cs.set.contains(@intCast(c));
            if (in_set != cs.inverted) table.set(@intCast(c));
        }
        try self.node_bitmap.put(self.allocator, node, table.bits);
        try self.writer.emitCharClass(opcode, &table.bits);
    }

    /// What the opcode's table holds: the set, or for `_INV` its complement.
    /// Owned by the caller (the generator's allocator).
    fn membersOf(self: *Self, cs: hir.CharSetNode) !CharSet {
        return if (cs.inverted) cs.set.complement(self.allocator) else cs.set.clone(self.allocator);
    }

    /// The table index of a `set`-encoded CharSet node, building and
    /// interning its entry on first use.
    fn charSetIndex(self: *Self, node: *const Node, cs: hir.CharSetNode) !u32 {
        if (self.node_charset.get(node)) |idx| return idx;
        const idx = try self.internCharSet(cs.encoding_hint, try self.membersOf(cs));
        try self.node_charset.put(self.allocator, node, idx);
        return idx;
    }

    /// Add `set` to the table (taking ownership) or, if an entry with the
    /// same hint and ranges is already there, free it and return that one's
    /// index. A new index is always the table's length: order of first
    /// appearance.
    fn internCharSet(self: *Self, hint: hir.EncodingHint, set: CharSet) !u32 {
        const key: CharSetKey = .{ .hint = hint, .ranges = set.ranges };
        if (self.charset_index.get(key)) |idx| {
            set.deinit(self.allocator);
            return idx;
        }
        if (self.programBytes() + set.byteSize() > MAX_PROGRAM_BYTES) {
            set.deinit(self.allocator);
            return error.PatternTooLarge;
        }
        const idx: u32 = @intCast(self.charsets.items.len);
        self.charsets.append(self.allocator, set) catch |err| {
            set.deinit(self.allocator);
            return err;
        };
        self.charset_bytes += set.byteSize();
        // On failure the set stays in `charsets` (freed by `deinit`); it's
        // just not findable for interning.
        try self.charset_index.put(self.allocator, key, idx);
        return idx;
    }

    // =========================================================================
    // Quantifiers
    // =========================================================================

    /// A Repeat, in the shape of the syntax that produced it
    /// (`hir.SyntaxForm`, semantic: only `question` clears its captures on
    /// skip).
    fn generateRepeat(self: *Self, r: hir.Repeat) !void {
        switch (r.policy) {
            .greedy => switch (r.syntax_form) {
                .star => try self.generateStar(r.body),
                .plus => try self.generatePlus(r.body),
                .question => try self.generateQuestion(r.body),
                .counted => try self.generateCounted(r, .SPLIT_GREEDY),
            },
            .lazy => switch (r.syntax_form) {
                .star => try self.generateLazyStar(r.body),
                .plus => try self.generateLazyPlus(r.body),
                .question => try self.generateLazyQuestion(r.body),
                .counted => try self.generateCounted(r, .SPLIT_LAZY),
            },
            .possessive => switch (r.syntax_form) {
                .star => try self.generatePossessiveStar(r.body),
                .plus => try self.generatePossessivePlus(r.body),
                .question => try self.generatePossessiveQuestion(r.body),
                .counted => return error.InvalidPattern,
            },
        }
    }

    /// Generate code for star quantifier: e*
    /// Pattern: L1: SPLIT_GREEDY L1_body, L2; L1_body: e; GOTO L1; L2: ...
    /// Greedy: try consuming (looping) before giving up, matching how
    /// `generatePlus`/`generateCounted`'s unbounded case already do it. The
    /// `isStarQuantifier`/`matchStarGreedy` fast path in
    /// `recursive_matcher.zig` is an optimization on top of this correct
    /// order (it works regardless of operand order, trying both), but any
    /// atom too complex for that heuristic to recognize (e.g. a capturing
    /// group or nested alternation) falls back to this bytecode's own
    /// SPLIT priority for correctness -- which is why this must be
    /// genuinely greedy-first, not just an optimization hint.
    fn generateStar(self: *Self, body: *const Node) !void {
        var loop_label = try self.writer.createLabel();
        var end_label = try self.writer.createLabel();

        try self.writer.defineLabel(&loop_label);
        try self.writer.emitSplit(.SPLIT_GREEDY, loop_label, end_label);

        try self.generateNode(body);
        try self.writer.emitJump(.GOTO, loop_label);

        try self.writer.defineLabel(&end_label);
    }

    /// Generate code for plus quantifier: e+
    /// Pattern: L1: e; SPLIT L1, L2; L2: ...
    fn generatePlus(self: *Self, body: *const Node) !void {
        var loop_label = try self.writer.createLabel();
        var end_label = try self.writer.createLabel();

        try self.writer.defineLabel(&loop_label);
        try self.generateNode(body);
        try self.writer.emitSplit(.SPLIT_GREEDY, loop_label, end_label); // Greedy

        try self.writer.defineLabel(&end_label);
    }

    /// Generate code for question quantifier: e?
    /// Pattern: SPLIT_GREEDY consume, skip; consume: e; skip: ...
    /// Greedy: try consuming first (matching how
    /// `generateLazyQuestion` already tries skip first for `e??`) so a plain
    /// try-first-then-backtrack-on-failure interpretation is correct
    /// regardless of whether `e` is simple enough for the
    /// `isQuestionQuantifier` fast-path heuristic to recognize -- see
    /// `generateStar`'s doc comment for why this matters for compound atoms
    /// like a capturing group.
    fn generateQuestion(self: *Self, body: *const Node) !void {
        var skip_label = try self.writer.createLabel();
        var consume_label = try self.writer.createLabel();

        // SPLIT_GREEDY: first path = consume (fall-through), second = skip
        try self.writer.emitSplit(.SPLIT_GREEDY, consume_label, skip_label);

        // Define consume label immediately (fall-through)
        try self.writer.defineLabel(&consume_label);
        try self.generateNode(body);

        // Define skip label (after the character), clearing any capture
        // groups nested inside the atom first -- see emitClearCapturesOnSkip.
        try self.emitClearCapturesOnSkip(body, &skip_label);
    }

    /// After generating an optional atom's "consume" bytecode, wire up the
    /// "skip" landing point. If the atom contains capture groups, they must
    /// be reset to unset when this point is reached via the SPLIT's skip
    /// branch (the atom didn't run this time -- e.g. `(b+)?` declining to
    /// match on a later iteration of an enclosing `*`, after an earlier
    /// iteration DID set its capture) but NOT when reached by falling
    /// through after a successful consume (the atom just ran and its
    /// capture should stand). So the consume path needs an explicit GOTO
    /// past a small CLEAR_CAPTURE block that only the skip branch flows
    /// into; when there's nothing to clear, this degenerates to the
    /// original plain fall-through/jump-target shape. Only the `?`/`??`
    /// forms do this (`hir.SyntaxForm`); `{0,1}` doesn't.
    fn emitClearCapturesOnSkip(self: *Self, atom: *const Node, skip_label: *Label) !void {
        var group_indices: std.ArrayListUnmanaged(u16) = .empty;
        defer group_indices.deinit(self.allocator);
        try hir.collectCaptures(atom, &group_indices, self.allocator);

        if (group_indices.items.len == 0) {
            try self.writer.defineLabel(skip_label);
            return;
        }

        var merge_label = try self.writer.createLabel();
        try self.writer.emitJump(.GOTO, merge_label);
        try self.writer.defineLabel(skip_label);
        for (group_indices.items) |g| {
            try self.writer.emit1(.CLEAR_CAPTURE, g);
        }
        try self.writer.defineLabel(&merge_label);
    }

    /// Generate code for a counted quantifier: e{n,m} (SPLIT_GREEDY) or
    /// e{n,m}? (SPLIT_LAZY). `min` copies of the body, then either a loop
    /// (`{n,}`) or `max - min` optional copies. The greedy form tries to
    /// consume first, the lazy one to skip first.
    fn generateCounted(self: *Self, r: hir.Repeat, split: Opcode) !void {
        // Generate min required repetitions
        for (0..r.min) |_| {
            try self.generateNode(r.body);
        }

        if (r.max) |max| {
            if (max <= r.min) return;
            // Generate optional repetitions up to max
            // Pattern for each optional: SPLIT consume|skip; consume: e; skip: ...
            for (0..max - r.min) |_| {
                var skip_label = try self.writer.createLabel();
                var consume_label = try self.writer.createLabel();

                if (split == .SPLIT_GREEDY) {
                    // Greedy: try to consume first (longer match preferred)
                    try self.writer.emitSplit(.SPLIT_GREEDY, consume_label, skip_label);
                } else {
                    // Lazy: try to skip first (minimal match preferred)
                    try self.writer.emitSplit(.SPLIT_LAZY, skip_label, consume_label);
                }
                try self.writer.defineLabel(&consume_label);
                try self.generateNode(r.body);
                try self.writer.defineLabel(&skip_label);
            }
        } else {
            // Pattern: {n,} = n required + e* (greedy) or e*? (lazy)
            // L1: SPLIT ...; e; GOTO L1; L2: ...
            var loop_label = try self.writer.createLabel();
            var end_label = try self.writer.createLabel();

            try self.writer.defineLabel(&loop_label);
            if (split == .SPLIT_GREEDY) {
                try self.writer.emitSplit(.SPLIT_GREEDY, loop_label, end_label);
            } else {
                try self.writer.emitSplit(.SPLIT_LAZY, end_label, loop_label);
            }
            try self.generateNode(r.body);
            try self.writer.emitJump(.GOTO, loop_label);
            try self.writer.defineLabel(&end_label);
        }
    }

    /// Generate code for lazy star quantifier: e*?
    /// Pattern: L1: SPLIT_LAZY L2, L3; e; GOTO L1; L2: ...
    /// Lazy = try empty first, then try consuming
    fn generateLazyStar(self: *Self, body: *const Node) !void {
        var loop_label = try self.writer.createLabel();
        var end_label = try self.writer.createLabel();

        try self.writer.defineLabel(&loop_label);
        try self.writer.emitSplit(.SPLIT_LAZY, end_label, loop_label);

        try self.generateNode(body);
        try self.writer.emitJump(.GOTO, loop_label);

        try self.writer.defineLabel(&end_label);
    }

    /// Generate code for lazy plus quantifier: e+?
    /// Pattern: L1: e; SPLIT_LAZY L2, L1; L2: ...
    /// Lazy = match once, then try exit before consuming more
    fn generateLazyPlus(self: *Self, body: *const Node) !void {
        var loop_label = try self.writer.createLabel();
        var end_label = try self.writer.createLabel();

        try self.writer.defineLabel(&loop_label);
        try self.generateNode(body);
        try self.writer.emitSplit(.SPLIT_LAZY, end_label, loop_label);

        try self.writer.defineLabel(&end_label);
    }

    /// Generate code for lazy question quantifier: e??
    /// Pattern: SPLIT_LAZY skip, consume; consume: e; skip: ...
    /// Lazy = try skip first, then try consuming
    fn generateLazyQuestion(self: *Self, body: *const Node) !void {
        var skip_label = try self.writer.createLabel();
        var consume_label = try self.writer.createLabel();

        // SPLIT_LAZY: first path = skip (don't consume), second path = consume
        // For lazy, we prefer skip (minimal match)
        try self.writer.emitSplit(.SPLIT_LAZY, skip_label, consume_label);

        // Define consume label immediately (fall-through)
        try self.writer.defineLabel(&consume_label);
        try self.generateNode(body);

        // Define skip label (after the character), clearing any capture
        // groups nested inside the atom first -- see emitClearCapturesOnSkip.
        try self.emitClearCapturesOnSkip(body, &skip_label);
    }

    /// Generate code for possessive star quantifier: e*+
    /// Pattern: L1: SPLIT_POSSESSIVE L2, L3; e; GOTO L1; L2: ...
    /// Possessive = consume all without backtracking
    fn generatePossessiveStar(self: *Self, body: *const Node) !void {
        var loop_label = try self.writer.createLabel();
        var end_label = try self.writer.createLabel();

        try self.writer.defineLabel(&loop_label);
        try self.writer.emitSplit(.SPLIT_POSSESSIVE, end_label, loop_label);

        try self.generateNode(body);
        try self.writer.emitJump(.GOTO, loop_label);

        try self.writer.defineLabel(&end_label);
    }

    /// Generate code for possessive plus quantifier: e++
    /// Pattern: e; L1: SPLIT_POSSESSIVE L2, L1; e; GOTO L1; L2: ...
    /// Possessive = match at least once, then consume all without backtracking
    fn generatePossessivePlus(self: *Self, body: *const Node) !void {
        var loop_label = try self.writer.createLabel();
        var end_label = try self.writer.createLabel();

        // Match at least once
        try self.generateNode(body);

        // Loop for more (possessive)
        try self.writer.defineLabel(&loop_label);
        try self.writer.emitSplit(.SPLIT_POSSESSIVE, end_label, loop_label);
        try self.generateNode(body);
        try self.writer.emitJump(.GOTO, loop_label);

        try self.writer.defineLabel(&end_label);
    }

    /// Generate code for possessive question quantifier: e?+
    /// Pattern: SPLIT_POSSESSIVE consume, skip; consume: e; skip: ...
    /// Possessive = try consuming once without backtracking (greedy first)
    fn generatePossessiveQuestion(self: *Self, body: *const Node) !void {
        var skip_label = try self.writer.createLabel();
        var consume_label = try self.writer.createLabel();

        // SPLIT_POSSESSIVE: Try greedy path (consume) first, no backtracking
        try self.writer.emitSplit(.SPLIT_POSSESSIVE, consume_label, skip_label);

        // Define consume label immediately (fall-through)
        try self.writer.defineLabel(&consume_label);
        try self.generateNode(body);

        // Define skip label (after the character)
        try self.writer.defineLabel(&skip_label);
    }

    // =========================================================================
    // Structural
    // =========================================================================

    /// Generate code for an n-ary alternation, nested to the left as the
    /// parser's binary alternation always was: `a|b|c` is `((a|b)|c)`.
    /// Pattern: SPLIT L_left, L_right; L_left: left; GOTO end; L_right: right; end:
    fn generateAlternation(self: *Self, items: []const *const Node) CodegenError!void {
        if (items.len < 2) return error.InvalidPattern;

        var left_label = try self.writer.createLabel();
        var right_label = try self.writer.createLabel();
        var end_label = try self.writer.createLabel();

        // Split to both branches
        try self.writer.emitSplit(.SPLIT, left_label, right_label);

        // Left branch: everything but the last alternative
        try self.writer.defineLabel(&left_label);
        if (items.len == 2) {
            try self.generateNode(items[0]);
        } else {
            try self.generateAlternation(items[0 .. items.len - 1]);
        }
        try self.writer.emitJump(.GOTO, end_label);

        // Right branch
        try self.writer.defineLabel(&right_label);
        try self.generateNode(items[items.len - 1]);

        try self.writer.defineLabel(&end_label);
    }

    /// Generate code for capture group: (...)
    fn generateGroup(self: *Self, c: hir.Capture) !void {
        // SAVE_START
        try self.writer.emit1(.SAVE_START, c.index);

        // Generate group content
        try self.generateNode(c.body);

        // SAVE_END
        try self.writer.emit1(.SAVE_END, c.index);
    }

    // =========================================================================
    // Assertions and backreferences
    // =========================================================================

    /// `^`/`$`: STRING_START/STRING_END (absolute) by default,
    /// LINE_START/LINE_END (line-boundary-aware) under `m`.
    fn generateAssert(self: *Self, kind: hir.AssertKind) !void {
        const opcode: Opcode = switch (kind) {
            .caret => if (self.flags.multiline) .LINE_START else .STRING_START,
            .dollar => if (self.flags.multiline) .LINE_END else .STRING_END,
            .word_boundary => .WORD_BOUNDARY,
            .not_word_boundary => .NOT_WORD_BOUNDARY,
        };
        try self.writer.emitSimple(opcode);
    }

    /// Generate code for backreference
    fn generateBackRef(self: *Self, b: hir.Backref) !void {
        if (b.indices.len != 1) return error.InvalidPattern;
        // Choose case-sensitive or case-insensitive based on the scope
        const opcode: Opcode = if (self.flags.ignore_case) .BACK_REF_I else .BACK_REF;
        try self.writer.emit1(opcode, b.indices[0]);
    }

    /// Generate code for a lookaround assertion: (?=...), (?!...), (?<=...)
    /// or (?<!...)
    fn generateLook(self: *Self, l: hir.Look) !void {
        const opcode: Opcode = if (l.behind)
            (if (l.negated) .NEGATIVE_LOOKBEHIND else .LOOKBEHIND)
        else
            (if (l.negated) .NEGATIVE_LOOKAHEAD else .LOOKAHEAD);

        // For simplicity, we don't use the length field for now
        // The executor will find the END marker by scanning forward
        try self.writer.emit1(opcode, 0);

        // Generate the lookaround pattern
        try self.generateNode(l.body);

        // Emit end marker
        try self.writer.emitSimple(if (l.behind) .LOOKBEHIND_END else .LOOKAHEAD_END);
    }
};
