//! Auto-generated from test262 (tc39/test262, RegExp subtree) by
//! scripts/extract_test262.py. Do not hand-edit -- regenerate instead.
//! See docs/ECMASCRIPT_COMPATIBILITY_PLAN.md Phase 6 for how/why.

pub const Kind = enum { test_, exec_array, exec_null };

pub const Case = struct {
    kind: Kind,
    pattern: []const u8,
    flags: []const u8,
    input: []const u8,
    expected_bool: bool = false,
    expected_captures: []const ?[]const u8 = &.{},
    file: []const u8,
};

pub const cases = [_]Case{
    .{ .kind = .test_, .pattern = "[/]", .flags = "", .input = "x", .expected_bool = false, .file = "built-ins/RegExp/regexp-class-chars.js" },
    .{ .kind = .test_, .pattern = "[//]", .flags = "", .input = "x", .expected_bool = false, .file = "built-ins/RegExp/regexp-class-chars.js" },
    .{ .kind = .exec_array, .pattern = "(a*)b\\1+", .flags = "", .input = "baaac", .expected_captures = &[_]?[]const u8{ "b", "" }, .file = "built-ins/RegExp/S15.10.2.9_A1_T5.js" },
    .{ .kind = .exec_array, .pattern = "([xu]\\d{2}([A-H]{2})?)\\1", .flags = "", .input = "x09x12x01x05u00FFu00FFx04x04x23", .expected_captures = &[_]?[]const u8{ "u00FFu00FF", "u00FF", "FF" }, .file = "built-ins/RegExp/S15.10.2.9_A1_T3.js" },
    .{ .kind = .exec_array, .pattern = "([xu]\\d{2}([A-H]{2})?)\\1", .flags = "", .input = "x09x12x01x01u00FFu00FFx04x04x23", .expected_captures = &[_]?[]const u8{ "x01x01", "x01", null }, .file = "built-ins/RegExp/S15.10.2.9_A1_T2.js" },
    .{ .kind = .exec_array, .pattern = "\\b(\\w+) \\1\\b", .flags = "", .input = "do you listen the the band", .expected_captures = &[_]?[]const u8{ "the the", "the" }, .file = "built-ins/RegExp/S15.10.2.9_A1_T1.js" },
    .{ .kind = .exec_array, .pattern = "[a-z]+", .flags = "", .input = "ABC def ghi", .expected_captures = &[_]?[]const u8{ "def" }, .file = "built-ins/RegExp/S15.10.2.8_A5_T2.js" },
    .{ .kind = .exec_array, .pattern = "[a-z]+", .flags = "ig", .input = "ABC def ghi", .expected_captures = &[_]?[]const u8{ "ABC" }, .file = "built-ins/RegExp/S15.10.2.8_A5_T1.js" },
    .{ .kind = .exec_array, .pattern = ".+", .flags = "", .input = "`1234567890-=~!@#$%^&*()_+", .expected_captures = &[_]?[]const u8{ "`1234567890-=~!@#$%^&*()_+" }, .file = "built-ins/RegExp/S15.10.2.8_A4_T8.js" },
    .{ .kind = .exec_array, .pattern = ".+", .flags = "", .input = "ABCDEFGHIJKLMNOPQRSTUVWXYZ", .expected_captures = &[_]?[]const u8{ "ABCDEFGHIJKLMNOPQRSTUVWXYZ" }, .file = "built-ins/RegExp/S15.10.2.8_A4_T7.js" },
    .{ .kind = .exec_array, .pattern = ".+", .flags = "", .input = "abcdefghijklmnopqrstuvwxyz", .expected_captures = &[_]?[]const u8{ "abcdefghijklmnopqrstuvwxyz" }, .file = "built-ins/RegExp/S15.10.2.8_A4_T6.js" },
    .{ .kind = .exec_array, .pattern = ".+", .flags = "", .input = "....", .expected_captures = &[_]?[]const u8{ "...." }, .file = "built-ins/RegExp/S15.10.2.8_A4_T5.js" },
    .{ .kind = .exec_array, .pattern = ".+", .flags = "", .input = "this is a *&^%$# test", .expected_captures = &[_]?[]const u8{ "this is a *&^%$# test" }, .file = "built-ins/RegExp/S15.10.2.8_A4_T4.js" },
    .{ .kind = .exec_array, .pattern = ".*a.*", .flags = "", .input = "this is a test", .expected_captures = &[_]?[]const u8{ "this is a test" }, .file = "built-ins/RegExp/S15.10.2.8_A4_T3.js" },
    .{ .kind = .exec_array, .pattern = ".+", .flags = "", .input = "line 1\nline 2", .expected_captures = &[_]?[]const u8{ "line 1" }, .file = "built-ins/RegExp/S15.10.2.8_A4_T2.js" },
    .{ .kind = .exec_array, .pattern = "ab.de", .flags = "", .input = "abcde", .expected_captures = &[_]?[]const u8{ "abcde" }, .file = "built-ins/RegExp/S15.10.2.8_A4_T1.js" },
    .{ .kind = .exec_array, .pattern = "(.{2}).+\\1", .flags = "", .input = "aabcdaabcd", .expected_captures = &[_]?[]const u8{ "aabcdaa", "aa" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T9.js" },
    .{ .kind = .exec_array, .pattern = "(aa).+\\1", .flags = "", .input = "aabcdaabcd", .expected_captures = &[_]?[]const u8{ "aabcdaa", "aa" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T8.js" },
    .{ .kind = .exec_array, .pattern = "(aa)bcd\\1", .flags = "", .input = "aabcdaabcd", .expected_captures = &[_]?[]const u8{ "aabcdaa", "aa" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T7.js" },
    .{ .kind = .exec_array, .pattern = "(.{3})(.{4})", .flags = "", .input = "abcdefgh", .expected_captures = &[_]?[]const u8{ "abcdefg", "abc", "defg" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T6.js" },
    .{ .kind = .exec_array, .pattern = "a(bc)d(ef)g", .flags = "", .input = "abcdefg", .expected_captures = &[_]?[]const u8{ "abcdefg", "bc", "ef" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T5.js" },
    .{ .kind = .exec_array, .pattern = "(abc)", .flags = "", .input = "abc", .expected_captures = &[_]?[]const u8{ "abc", "abc" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T4.js" },
    .{ .kind = .exec_array, .pattern = "a|(b)", .flags = "", .input = "a", .expected_captures = &[_]?[]const u8{ "a", null }, .file = "built-ins/RegExp/S15.10.2.8_A3_T27.js" },
    .{ .kind = .exec_array, .pattern = "(a)?a", .flags = "", .input = "a", .expected_captures = &[_]?[]const u8{ "a", null }, .file = "built-ins/RegExp/S15.10.2.8_A3_T26.js" },
    .{ .kind = .exec_array, .pattern = "(A)?(A.*)", .flags = "", .input = "zxcasd;fl\\  ^AaaAAaaaf;lrlrzs", .expected_captures = &[_]?[]const u8{ "AaaAAaaaf;lrlrzs", null, "AaaAAaaaf;lrlrzs" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T25.js" },
    .{ .kind = .exec_array, .pattern = "(A)?(A.*)", .flags = "", .input = "zxcasd;fl\\  ^AAaaAAaaaf;lrlrzs", .expected_captures = &[_]?[]const u8{ "AAaaAAaaaf;lrlrzs", "A", "AaaAAaaaf;lrlrzs" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T24.js" },
    .{ .kind = .exec_array, .pattern = "(A)?(A.*)", .flags = "", .input = "zxcasd;fl\\  ^AAAaaAAaaaf;lrlrzs", .expected_captures = &[_]?[]const u8{ "AAAaaAAaaaf;lrlrzs", "A", "AAaaAAaaaf;lrlrzs" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T23.js" },
    .{ .kind = .exec_array, .pattern = "^(A)?(A.*)$", .flags = "", .input = "A", .expected_captures = &[_]?[]const u8{ "A", null, "A" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T22.js" },
    .{ .kind = .exec_array, .pattern = "^(A)?(A.*)$", .flags = "", .input = "AA", .expected_captures = &[_]?[]const u8{ "AA", "A", "A" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T21.js" },
    .{ .kind = .exec_array, .pattern = "^(A)?(A.*)$", .flags = "", .input = "AAA", .expected_captures = &[_]?[]const u8{ "AAA", "A", "AA" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T20.js" },
    .{ .kind = .exec_array, .pattern = "([Jj]ava([Ss]cript)?)\\sis\\s(fun\\w*)", .flags = "", .input = "Developing with Java is fun, try it", .expected_captures = &[_]?[]const u8{ "Java is fun", "Java", null, "fun" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T2.js" },
    .{ .kind = .exec_array, .pattern = "([\\S]+([ \\t]+[\\S]+)*)[ \\t]*=[ \\t]*[\\S]+", .flags = "", .input = "Course_Creator = Test", .expected_captures = &[_]?[]const u8{ "Course_Creator = Test", "Course_Creator", null }, .file = "built-ins/RegExp/S15.10.2.8_A3_T19.js" },
    .{ .kind = .exec_array, .pattern = "a(.?)b\\1c\\1d\\1", .flags = "", .input = "abcd", .expected_captures = &[_]?[]const u8{ "abcd", "" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T14.js" },
    .{ .kind = .exec_array, .pattern = "(a(b(c)))(d(e(f)))\\2\\5", .flags = "", .input = "xabcdefbcefg", .expected_captures = &[_]?[]const u8{ "abcdefbcef", "abc", "bc", "c", "def", "ef", "f" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T13.js" },
    .{ .kind = .exec_array, .pattern = "(a(b(c)))(d(e(f)))", .flags = "", .input = "xabcdefg", .expected_captures = &[_]?[]const u8{ "abcdef", "abc", "bc", "c", "def", "ef", "f" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T12.js" },
    .{ .kind = .exec_array, .pattern = "a(..(..)..)", .flags = "", .input = "abcdefgh", .expected_captures = &[_]?[]const u8{ "abcdefg", "bcdefg", "de" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T11.js" },
    .{ .kind = .exec_array, .pattern = "(\\d{3})(\\d{3})\\1\\2", .flags = "", .input = "123456123456", .expected_captures = &[_]?[]const u8{ "123456123456", "123", "456" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T10.js" },
    .{ .kind = .exec_array, .pattern = "([Jj]ava([Ss]cript)?)\\sis\\s(fun\\w*)", .flags = "", .input = "Learning javaScript is funny, really", .expected_captures = &[_]?[]const u8{ "javaScript is funny", "javaScript", "Script", "funny" }, .file = "built-ins/RegExp/S15.10.2.8_A3_T1.js" },
    .{ .kind = .exec_array, .pattern = "(?!a|b)|c", .flags = "", .input = "", .expected_captures = &[_]?[]const u8{ "" }, .file = "built-ins/RegExp/S15.10.2.8_A2_T9.js" },
    .{ .kind = .exec_array, .pattern = "Java(?!Script)([A-Z]\\w*)", .flags = "", .input = "JavaScr oops ipt ", .expected_captures = &[_]?[]const u8{ "JavaScr", "Scr" }, .file = "built-ins/RegExp/S15.10.2.8_A2_T5.js" },
    .{ .kind = .exec_array, .pattern = "Java(?!Script)([A-Z]\\w*)", .flags = "", .input = "using of JavaBeans technology", .expected_captures = &[_]?[]const u8{ "JavaBeans", "Beans" }, .file = "built-ins/RegExp/S15.10.2.8_A2_T2.js" },
    .{ .kind = .exec_array, .pattern = "(?!a|b)|c", .flags = "", .input = "d", .expected_captures = &[_]?[]const u8{ "" }, .file = "built-ins/RegExp/S15.10.2.8_A2_T11.js" },
    .{ .kind = .exec_array, .pattern = "(?!a|b)|c", .flags = "", .input = "bc", .expected_captures = &[_]?[]const u8{ "" }, .file = "built-ins/RegExp/S15.10.2.8_A2_T10.js" },
    .{ .kind = .exec_array, .pattern = "(.*?)a(?!(a+)b\\2c)\\2(.*)", .flags = "", .input = "baaabaac", .expected_captures = &[_]?[]const u8{ "baaabaac", "ba", null, "abaac" }, .file = "built-ins/RegExp/S15.10.2.8_A2_T1.js" },
    .{ .kind = .exec_array, .pattern = "[Jj]ava([Ss]cript)?(?=\\:)", .flags = "", .input = "taste of java: the cookbook ", .expected_captures = &[_]?[]const u8{ "java", null }, .file = "built-ins/RegExp/S15.10.2.8_A1_T4.js" },
    .{ .kind = .exec_array, .pattern = "[Jj]ava([Ss]cript)?(?=\\:)", .flags = "", .input = "just Javascript: the way af jedi", .expected_captures = &[_]?[]const u8{ "Javascript", "script" }, .file = "built-ins/RegExp/S15.10.2.8_A1_T3.js" },
    .{ .kind = .exec_array, .pattern = "(?=(a+))a*b\\1", .flags = "", .input = "baaabac", .expected_captures = &[_]?[]const u8{ "aba", "a" }, .file = "built-ins/RegExp/S15.10.2.8_A1_T2.js" },
    .{ .kind = .exec_array, .pattern = "(?=(a+))", .flags = "", .input = "baaabac", .expected_captures = &[_]?[]const u8{ "", "aaa" }, .file = "built-ins/RegExp/S15.10.2.8_A1_T1.js" },
    .{ .kind = .exec_array, .pattern = "x{1,2}x{1,}", .flags = "", .input = "xxxxxxx", .expected_captures = &[_]?[]const u8{ "xxxxxxx" }, .file = "built-ins/RegExp/S15.10.2.7_A6_T6.js" },
    .{ .kind = .exec_array, .pattern = "(123){1,}x\\1", .flags = "", .input = "123123x123", .expected_captures = &[_]?[]const u8{ "123123x123", "123" }, .file = "built-ins/RegExp/S15.10.2.7_A6_T5.js" },
    .{ .kind = .exec_array, .pattern = "(123){1,}", .flags = "", .input = "123123", .expected_captures = &[_]?[]const u8{ "123123", "123" }, .file = "built-ins/RegExp/S15.10.2.7_A6_T4.js" },
    .{ .kind = .exec_array, .pattern = "\\d{1,}", .flags = "", .input = "wqe456646dsff", .expected_captures = &[_]?[]const u8{ "456646" }, .file = "built-ins/RegExp/S15.10.2.7_A6_T3.js" },
    .{ .kind = .exec_array, .pattern = "b{2,}c", .flags = "", .input = "aaabbbbcccddeeeefffff", .expected_captures = &[_]?[]const u8{ "bbbbc" }, .file = "built-ins/RegExp/S15.10.2.7_A6_T1.js" },
    .{ .kind = .exec_array, .pattern = "b?b?b?b", .flags = "", .input = "abbbbc", .expected_captures = &[_]?[]const u8{ "bbbb" }, .file = "built-ins/RegExp/S15.10.2.7_A5_T9.js" },
    .{ .kind = .exec_array, .pattern = "x?ay?bz?c", .flags = "", .input = "abcd", .expected_captures = &[_]?[]const u8{ "abc" }, .file = "built-ins/RegExp/S15.10.2.7_A5_T8.js" },
    .{ .kind = .exec_array, .pattern = "x?y?z?", .flags = "", .input = "abcd", .expected_captures = &[_]?[]const u8{ "" }, .file = "built-ins/RegExp/S15.10.2.7_A5_T7.js" },
    .{ .kind = .exec_array, .pattern = "o?pqrst", .flags = "", .input = "pqrstuvw", .expected_captures = &[_]?[]const u8{ "pqrst" }, .file = "built-ins/RegExp/S15.10.2.7_A5_T6.js" },
    .{ .kind = .exec_array, .pattern = "cdx?e", .flags = "", .input = "abcdef", .expected_captures = &[_]?[]const u8{ "cde" }, .file = "built-ins/RegExp/S15.10.2.7_A5_T5.js" },
    .{ .kind = .exec_array, .pattern = "cd?e", .flags = "", .input = "abcdef", .expected_captures = &[_]?[]const u8{ "cde" }, .file = "built-ins/RegExp/S15.10.2.7_A5_T4.js" },
    .{ .kind = .exec_array, .pattern = "java(script)?", .flags = "", .input = "state: java and javascript are vastly different", .expected_captures = &[_]?[]const u8{ "java", null }, .file = "built-ins/RegExp/S15.10.2.7_A5_T2.js" },
    .{ .kind = .exec_array, .pattern = ".?.?.?.?.?.?.?", .flags = "", .input = "test", .expected_captures = &[_]?[]const u8{ "test" }, .file = "built-ins/RegExp/S15.10.2.7_A5_T12.js" },
    .{ .kind = .exec_array, .pattern = "\\??\\??\\??\\??\\??", .flags = "", .input = "?????", .expected_captures = &[_]?[]const u8{ "?????" }, .file = "built-ins/RegExp/S15.10.2.7_A5_T11.js" },
    .{ .kind = .exec_array, .pattern = "ab?c?d?x?y?z", .flags = "", .input = "123az789", .expected_captures = &[_]?[]const u8{ "az" }, .file = "built-ins/RegExp/S15.10.2.7_A5_T10.js" },
    .{ .kind = .exec_array, .pattern = "java(script)?", .flags = "", .input = "state: javascript is extension of ecma script", .expected_captures = &[_]?[]const u8{ "javascript", "script" }, .file = "built-ins/RegExp/S15.10.2.7_A5_T1.js" },
    .{ .kind = .exec_array, .pattern = "[^\"]*", .flags = "", .input = "before'i'start", .expected_captures = &[_]?[]const u8{ "before'i'start" }, .file = "built-ins/RegExp/S15.10.2.7_A4_T3.js" },
    .{ .kind = .exec_array, .pattern = "d+", .flags = "", .input = "abcdddddefg", .expected_captures = &[_]?[]const u8{ "ddddd" }, .file = "built-ins/RegExp/S15.10.2.7_A3_T9.js" },
    .{ .kind = .exec_array, .pattern = "[a-z]+(\\d+)", .flags = "", .input = "__abc123.0", .expected_captures = &[_]?[]const u8{ "abc123", "123" }, .file = "built-ins/RegExp/S15.10.2.7_A3_T8.js" },
    .{ .kind = .exec_array, .pattern = "[a-z]+(\\d+)", .flags = "", .input = "x 2 ff 55 x2 as1 z12 abc12.0", .expected_captures = &[_]?[]const u8{ "x2", "2" }, .file = "built-ins/RegExp/S15.10.2.7_A3_T7.js" },
    .{ .kind = .exec_array, .pattern = "[a-z]+\\d+", .flags = "", .input = "__abc123.0", .expected_captures = &[_]?[]const u8{ "abc123" }, .file = "built-ins/RegExp/S15.10.2.7_A3_T6.js" },
    .{ .kind = .exec_array, .pattern = "[a-z]+\\d+", .flags = "", .input = "x 2 ff 55 x2 as1 z12 abc12.0", .expected_captures = &[_]?[]const u8{ "x2" }, .file = "built-ins/RegExp/S15.10.2.7_A3_T5.js" },
    .{ .kind = .exec_array, .pattern = "\\s+java\\s+", .flags = "", .input = "\t java object", .expected_captures = &[_]?[]const u8{ "\t java " }, .file = "built-ins/RegExp/S15.10.2.7_A3_T2.js" },
    .{ .kind = .exec_array, .pattern = "b*b+", .flags = "", .input = "abbbbbbbc", .expected_captures = &[_]?[]const u8{ "bbbbbbb" }, .file = "built-ins/RegExp/S15.10.2.7_A3_T14.js" },
    .{ .kind = .exec_array, .pattern = "(b+)(b*)", .flags = "", .input = "abbbbbbbc", .expected_captures = &[_]?[]const u8{ "bbbbbbb", "bbbbbbb", "" }, .file = "built-ins/RegExp/S15.10.2.7_A3_T13.js" },
    .{ .kind = .exec_array, .pattern = "(b+)(b+)(b+)", .flags = "", .input = "abbbbbbbc", .expected_captures = &[_]?[]const u8{ "bbbbbbb", "bbbbb", "b", "b" }, .file = "built-ins/RegExp/S15.10.2.7_A3_T12.js" },
    .{ .kind = .exec_array, .pattern = "d+", .flags = "", .input = "abcdefg", .expected_captures = &[_]?[]const u8{ "d" }, .file = "built-ins/RegExp/S15.10.2.7_A3_T11.js" },
    .{ .kind = .exec_array, .pattern = "\\s+java\\s+", .flags = "", .input = "language  java\n", .expected_captures = &[_]?[]const u8{ "  java\n" }, .file = "built-ins/RegExp/S15.10.2.7_A3_T1.js" },
    .{ .kind = .exec_array, .pattern = "b{2}c", .flags = "", .input = "aaabbbbcccddeeeefffff", .expected_captures = &[_]?[]const u8{ "bbc" }, .file = "built-ins/RegExp/S15.10.2.7_A2_T3.js" },
    .{ .kind = .exec_array, .pattern = "\\w{3}\\d?", .flags = "", .input = "CELL￝box127", .expected_captures = &[_]?[]const u8{ "CEL" }, .file = "built-ins/RegExp/S15.10.2.7_A2_T2.js" },
    .{ .kind = .exec_array, .pattern = "\\w{3}\\d?", .flags = "", .input = "CE￿L￝box127", .expected_captures = &[_]?[]const u8{ "box1" }, .file = "built-ins/RegExp/S15.10.2.7_A2_T1.js" },
    .{ .kind = .exec_array, .pattern = "b{2,3}c", .flags = "", .input = "aaabbbbcccddeeeefffff", .expected_captures = &[_]?[]const u8{ "bbbc" }, .file = "built-ins/RegExp/S15.10.2.7_A1_T8.js" },
    .{ .kind = .exec_array, .pattern = "\\d{2,4}", .flags = "", .input = "0a01122b", .expected_captures = &[_]?[]const u8{ "0112" }, .file = "built-ins/RegExp/S15.10.2.7_A1_T7.js" },
    .{ .kind = .exec_array, .pattern = "\\d{2,4}", .flags = "", .input = "0a011b", .expected_captures = &[_]?[]const u8{ "011" }, .file = "built-ins/RegExp/S15.10.2.7_A1_T6.js" },
    .{ .kind = .exec_array, .pattern = "\\d{2,4}", .flags = "", .input = "the 1984 novel", .expected_captures = &[_]?[]const u8{ "1984" }, .file = "built-ins/RegExp/S15.10.2.7_A1_T5.js" },
    .{ .kind = .exec_array, .pattern = "\\d{2,4}", .flags = "", .input = "the Fahrenheit 451 book", .expected_captures = &[_]?[]const u8{ "451" }, .file = "built-ins/RegExp/S15.10.2.7_A1_T4.js" },
    .{ .kind = .exec_array, .pattern = "\\d{2,4}", .flags = "", .input = "the 20000 Leagues Under the Sea book", .expected_captures = &[_]?[]const u8{ "2000" }, .file = "built-ins/RegExp/S15.10.2.7_A1_T3.js" },
    .{ .kind = .exec_array, .pattern = ".{0,93}", .flags = "", .input = "weirwerdf", .expected_captures = &[_]?[]const u8{ "weirwerdf" }, .file = "built-ins/RegExp/S15.10.2.7_A1_T12.js" },
    .{ .kind = .exec_array, .pattern = "bx{0,93}c", .flags = "", .input = "aaabbbbcccddeeeefffff", .expected_captures = &[_]?[]const u8{ "bc" }, .file = "built-ins/RegExp/S15.10.2.7_A1_T11.js" },
    .{ .kind = .exec_array, .pattern = "b{0,93}c", .flags = "", .input = "aaabbbbcccddeeeefffff", .expected_captures = &[_]?[]const u8{ "bbbbc" }, .file = "built-ins/RegExp/S15.10.2.7_A1_T10.js" },
    .{ .kind = .exec_array, .pattern = "\\d{2,4}", .flags = "", .input = "the answer is 42", .expected_captures = &[_]?[]const u8{ "42" }, .file = "built-ins/RegExp/S15.10.2.7_A1_T1.js" },
    .{ .kind = .exec_array, .pattern = "^.*(:|$)", .flags = "", .input = "Hello: World", .expected_captures = &[_]?[]const u8{ "Hello: World", "" }, .file = "built-ins/RegExp/S15.10.2.6_A6_T4.js" },
    .{ .kind = .exec_array, .pattern = "^.*?(:|$)", .flags = "", .input = "Hello: World", .expected_captures = &[_]?[]const u8{ "Hello:", ":" }, .file = "built-ins/RegExp/S15.10.2.6_A6_T3.js" },
    .{ .kind = .exec_array, .pattern = "^.*?", .flags = "", .input = "Hello World", .expected_captures = &[_]?[]const u8{ "" }, .file = "built-ins/RegExp/S15.10.2.6_A6_T2.js" },
    .{ .kind = .exec_array, .pattern = "^.*?$", .flags = "", .input = "Hello World", .expected_captures = &[_]?[]const u8{ "Hello World" }, .file = "built-ins/RegExp/S15.10.2.6_A6_T1.js" },
    .{ .kind = .exec_array, .pattern = "\\B\\B\\B\\B\\B\\Bbot\\b\\b\\b\\b\\b\\b\\b", .flags = "", .input = "robot wall-e", .expected_captures = &[_]?[]const u8{ "bot" }, .file = "built-ins/RegExp/S15.10.2.6_A5_T2.js" },
    .{ .kind = .exec_array, .pattern = "^^^^^^^robot$$$$", .flags = "", .input = "robot", .expected_captures = &[_]?[]const u8{ "robot" }, .file = "built-ins/RegExp/S15.10.2.6_A5_T1.js" },
    .{ .kind = .exec_array, .pattern = "\\B\\w{4}\\B", .flags = "", .input = "devil arise\tforzzx\nevils", .expected_captures = &[_]?[]const u8{ "orzz" }, .file = "built-ins/RegExp/S15.10.2.6_A4_T8.js" },
    .{ .kind = .exec_array, .pattern = "\\B[^z]{4}\\B", .flags = "", .input = "devil arise\tforzzx\nevils", .expected_captures = &[_]?[]const u8{ "il a" }, .file = "built-ins/RegExp/S15.10.2.6_A4_T7.js" },
    .{ .kind = .exec_array, .pattern = "\\B\\w", .flags = "", .input = "devils arise\tfor\nrevil", .expected_captures = &[_]?[]const u8{ "e" }, .file = "built-ins/RegExp/S15.10.2.6_A4_T6.js" },
    .{ .kind = .exec_array, .pattern = "\\w\\B", .flags = "", .input = "devils arise\tfor\nrevil", .expected_captures = &[_]?[]const u8{ "d" }, .file = "built-ins/RegExp/S15.10.2.6_A4_T5.js" },
    .{ .kind = .exec_array, .pattern = "\\B\\w\\B", .flags = "", .input = "devils arise\tfor\nrevil", .expected_captures = &[_]?[]const u8{ "e" }, .file = "built-ins/RegExp/S15.10.2.6_A4_T4.js" },
    .{ .kind = .exec_array, .pattern = "\\Bo\\B", .flags = "i", .input = "devils arise\tfOr\nrevil", .expected_captures = &[_]?[]const u8{ "O" }, .file = "built-ins/RegExp/S15.10.2.6_A4_T3.js" },
    .{ .kind = .exec_array, .pattern = "[f-z]e\\B", .flags = "", .input = "devils arise\tfor\nrevil", .expected_captures = &[_]?[]const u8{ "re" }, .file = "built-ins/RegExp/S15.10.2.6_A4_T2.js" },
    .{ .kind = .exec_array, .pattern = "\\Bevil\\B", .flags = "", .input = "devils arise\tfor\nevil", .expected_captures = &[_]?[]const u8{ "evil" }, .file = "built-ins/RegExp/S15.10.2.6_A4_T1.js" },
    .{ .kind = .exec_array, .pattern = "\\bro", .flags = "", .input = "pilot\nsoviet robot\topenoffice", .expected_captures = &[_]?[]const u8{ "ro" }, .file = "built-ins/RegExp/S15.10.2.6_A3_T8.js" },
    .{ .kind = .exec_array, .pattern = "[^o]t\\b", .flags = "i", .input = "pilOt\nsoviet robot\topenoffice", .expected_captures = &[_]?[]const u8{ "et" }, .file = "built-ins/RegExp/S15.10.2.6_A3_T7.js" },
    .{ .kind = .exec_array, .pattern = "[^o]t\\b", .flags = "", .input = "pilOt\nsoviet robot\topenoffice", .expected_captures = &[_]?[]const u8{ "Ot" }, .file = "built-ins/RegExp/S15.10.2.6_A3_T6.js" },
    .{ .kind = .exec_array, .pattern = "\\bso", .flags = "", .input = "pilot\nsoviet robot\topenoffice", .expected_captures = &[_]?[]const u8{ "so" }, .file = "built-ins/RegExp/S15.10.2.6_A3_T4.js" },
    .{ .kind = .exec_array, .pattern = "ot\\b", .flags = "", .input = "pilot\nsoviet robot\topenoffice", .expected_captures = &[_]?[]const u8{ "ot" }, .file = "built-ins/RegExp/S15.10.2.6_A3_T2.js" },
    .{ .kind = .exec_array, .pattern = "e\\b", .flags = "", .input = "pilot\nsoviet robot\topenoffice", .expected_captures = &[_]?[]const u8{ "e" }, .file = "built-ins/RegExp/S15.10.2.6_A3_T14.js" },
    .{ .kind = .exec_array, .pattern = "\\bop", .flags = "", .input = "pilot\nsoviet robot\topenoffice", .expected_captures = &[_]?[]const u8{ "op" }, .file = "built-ins/RegExp/S15.10.2.6_A3_T12.js" },
    .{ .kind = .exec_array, .pattern = "\\b\\w{5}\\b", .flags = "", .input = "pilot\nsoviet robot\topenoffice", .expected_captures = &[_]?[]const u8{ "pilot" }, .file = "built-ins/RegExp/S15.10.2.6_A3_T11.js" },
    .{ .kind = .exec_array, .pattern = "\\brobot\\b", .flags = "", .input = "pilot\nsoviet robot\topenoffice", .expected_captures = &[_]?[]const u8{ "robot" }, .file = "built-ins/RegExp/S15.10.2.6_A3_T10.js" },
    .{ .kind = .exec_array, .pattern = "\\bp", .flags = "", .input = "pilot\nsoviet robot\topenoffice", .expected_captures = &[_]?[]const u8{ "p" }, .file = "built-ins/RegExp/S15.10.2.6_A3_T1.js" },
    .{ .kind = .exec_array, .pattern = "^\\^+", .flags = "", .input = "^^^x", .expected_captures = &[_]?[]const u8{ "^^^" }, .file = "built-ins/RegExp/S15.10.2.6_A2_T9.js" },
    .{ .kind = .exec_array, .pattern = "^ab", .flags = "", .input = "abcde", .expected_captures = &[_]?[]const u8{ "ab" }, .file = "built-ins/RegExp/S15.10.2.6_A2_T6.js" },
    .{ .kind = .exec_array, .pattern = "^[^p]", .flags = "m", .input = "pairs\nmakes\tdouble\npesos", .expected_captures = &[_]?[]const u8{ "m" }, .file = "built-ins/RegExp/S15.10.2.6_A2_T5.js" },
    .{ .kind = .exec_array, .pattern = "^p[b-z]", .flags = "m", .input = "pairs\nmakes\tdouble\npesos", .expected_captures = &[_]?[]const u8{ "pe" }, .file = "built-ins/RegExp/S15.10.2.6_A2_T4.js" },
    .{ .kind = .exec_array, .pattern = "^p[a-z]", .flags = "", .input = "pairs\nmakes\tdouble\npesos", .expected_captures = &[_]?[]const u8{ "pa" }, .file = "built-ins/RegExp/S15.10.2.6_A2_T3.js" },
    .{ .kind = .exec_array, .pattern = "^m", .flags = "m", .input = "pairs\nmakes\tdouble", .expected_captures = &[_]?[]const u8{ "m" }, .file = "built-ins/RegExp/S15.10.2.6_A2_T2.js" },
    .{ .kind = .exec_array, .pattern = "^\\d+", .flags = "m", .input = "abc\n123xyz", .expected_captures = &[_]?[]const u8{ "123" }, .file = "built-ins/RegExp/S15.10.2.6_A2_T10.js" },
    .{ .kind = .exec_array, .pattern = "es$", .flags = "mg", .input = "pairs\nmakes\tdoubles", .expected_captures = &[_]?[]const u8{ "es" }, .file = "built-ins/RegExp/S15.10.2.6_A1_T5.js" },
    .{ .kind = .exec_array, .pattern = "[^e]$", .flags = "mg", .input = "pairs\nmakes\tdouble", .expected_captures = &[_]?[]const u8{ "s" }, .file = "built-ins/RegExp/S15.10.2.6_A1_T4.js" },
    .{ .kind = .exec_array, .pattern = "s$", .flags = "m", .input = "pairs\nmakes\tdouble", .expected_captures = &[_]?[]const u8{ "s" }, .file = "built-ins/RegExp/S15.10.2.6_A1_T3.js" },
    .{ .kind = .exec_array, .pattern = "e$", .flags = "", .input = "pairs\nmakes\tdouble", .expected_captures = &[_]?[]const u8{ "e" }, .file = "built-ins/RegExp/S15.10.2.6_A1_T2.js" },
    .{ .kind = .exec_array, .pattern = "(a*)b\\1+", .flags = "", .input = "baaaac", .expected_captures = &[_]?[]const u8{ "b", "" }, .file = "built-ins/RegExp/S15.10.2.5_A1_T5.js" },
    .{ .kind = .exec_array, .pattern = "(z)((a+)?(b+)?(c))*", .flags = "", .input = "zaacbbbcac", .expected_captures = &[_]?[]const u8{ "zaacbbbcac", "z", "ac", "a", null, "c" }, .file = "built-ins/RegExp/S15.10.2.5_A1_T4.js" },
    .{ .kind = .exec_array, .pattern = "(aa|aabaac|ba|b|c)*", .flags = "", .input = "aabaac", .expected_captures = &[_]?[]const u8{ "aaba", "ba" }, .file = "built-ins/RegExp/S15.10.2.5_A1_T3.js" },
    .{ .kind = .exec_array, .pattern = "a[a-z]{2,4}?", .flags = "", .input = "abcdefghi", .expected_captures = &[_]?[]const u8{ "abc" }, .file = "built-ins/RegExp/S15.10.2.5_A1_T2.js" },
    .{ .kind = .exec_array, .pattern = "a[a-z]{2,4}", .flags = "", .input = "abcdefghi", .expected_captures = &[_]?[]const u8{ "abcde" }, .file = "built-ins/RegExp/S15.10.2.5_A1_T1.js" },
    .{ .kind = .exec_array, .pattern = "(?:ab|cd)+|ef", .flags = "i", .input = "AEKFCDab", .expected_captures = &[_]?[]const u8{ "CDab" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T9.js" },
    .{ .kind = .exec_array, .pattern = "(?:ab|cd)+|ef", .flags = "i", .input = "AEKFCD", .expected_captures = &[_]?[]const u8{ "CD" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T8.js" },
    .{ .kind = .exec_array, .pattern = "ab|cd|ef", .flags = "i", .input = "AEKFCD", .expected_captures = &[_]?[]const u8{ "CD" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T6.js" },
    .{ .kind = .exec_array, .pattern = "\\d{3}|[a-z]{4}", .flags = "", .input = "2, 12 and 234 AND of course repeat 12", .expected_captures = &[_]?[]const u8{ "234" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T4.js" },
    .{ .kind = .exec_array, .pattern = "\\d{3}|[a-z]{4}", .flags = "", .input = "2, 12 and of course repeat 12", .expected_captures = &[_]?[]const u8{ "cour" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T3.js" },
    .{ .kind = .exec_array, .pattern = "((a)|(ab))((c)|(bc))", .flags = "", .input = "abc", .expected_captures = &[_]?[]const u8{ "abc", "a", "a", null, "bc", null, "bc" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T2.js" },
    .{ .kind = .exec_array, .pattern = "|()", .flags = "", .input = "", .expected_captures = &[_]?[]const u8{ "", null }, .file = "built-ins/RegExp/S15.10.2.3_A1_T17.js" },
    .{ .kind = .exec_array, .pattern = "()|", .flags = "", .input = "", .expected_captures = &[_]?[]const u8{ "", "" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T16.js" },
    .{ .kind = .exec_array, .pattern = "(Rob)|(Bob)|(Robert)|(Bobby)", .flags = "", .input = "Hi Bob", .expected_captures = &[_]?[]const u8{ "Bob", null, "Bob", null, null }, .file = "built-ins/RegExp/S15.10.2.3_A1_T15.js" },
    .{ .kind = .exec_array, .pattern = ".+: gr(a|e)y", .flags = "", .input = "color: grey", .expected_captures = &[_]?[]const u8{ "color: grey", "e" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T14.js" },
    .{ .kind = .exec_array, .pattern = "(.)..|abc", .flags = "", .input = "abc", .expected_captures = &[_]?[]const u8{ "abc", "a" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T13.js" },
    .{ .kind = .exec_array, .pattern = "xyz|...", .flags = "", .input = "abc", .expected_captures = &[_]?[]const u8{ "abc" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T12.js" },
    .{ .kind = .exec_array, .pattern = "11111|111", .flags = "", .input = "1111111111111111", .expected_captures = &[_]?[]const u8{ "11111" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T11.js" },
    .{ .kind = .exec_array, .pattern = "(?:ab|cd)+|ef", .flags = "i", .input = "AEKeFCDab", .expected_captures = &[_]?[]const u8{ "eF" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T10.js" },
    .{ .kind = .exec_array, .pattern = "a|ab", .flags = "", .input = "abc", .expected_captures = &[_]?[]const u8{ "a" }, .file = "built-ins/RegExp/S15.10.2.3_A1_T1.js" },
    .{ .kind = .exec_array, .pattern = "[^\\[\\b\\]]+", .flags = "", .input = "abcdef", .expected_captures = &[_]?[]const u8{ "abcdef" }, .file = "built-ins/RegExp/S15.10.2.13_A3_T4.js" },
    .{ .kind = .exec_array, .pattern = "[^\\[\\b\\]]+", .flags = "", .input = "abc\x08def", .expected_captures = &[_]?[]const u8{ "abc" }, .file = "built-ins/RegExp/S15.10.2.13_A3_T3.js" },
    .{ .kind = .exec_array, .pattern = "c[\\b]{3}d", .flags = "", .input = "abc\x08\x08\x08def", .expected_captures = &[_]?[]const u8{ "c\x08\x08\x08d" }, .file = "built-ins/RegExp/S15.10.2.13_A3_T2.js" },
    .{ .kind = .exec_array, .pattern = ".[\\b].", .flags = "", .input = "abc\x08def", .expected_captures = &[_]?[]const u8{ "c\x08d" }, .file = "built-ins/RegExp/S15.10.2.13_A3_T1.js" },
    .{ .kind = .exec_array, .pattern = "[^]", .flags = "", .input = "abc#$%def%&*@ghi", .expected_captures = &[_]?[]const u8{ "a" }, .file = "built-ins/RegExp/S15.10.2.13_A2_T8.js" },
    .{ .kind = .exec_array, .pattern = "[^a-z]{4}", .flags = "", .input = "abc#$%def%&*@ghi", .expected_captures = &[_]?[]const u8{ "%&*@" }, .file = "built-ins/RegExp/S15.10.2.13_A2_T7.js" },
    .{ .kind = .exec_array, .pattern = "a[^1-9]c", .flags = "", .input = "abc", .expected_captures = &[_]?[]const u8{ "abc" }, .file = "built-ins/RegExp/S15.10.2.13_A2_T5.js" },
    .{ .kind = .exec_array, .pattern = "[^\\b]+", .flags = "g", .input = "easy\x08to\x08ride", .expected_captures = &[_]?[]const u8{ "easy" }, .file = "built-ins/RegExp/S15.10.2.13_A2_T4.js" },
    .{ .kind = .exec_array, .pattern = "a[^b-z]\\s+", .flags = "", .input = "ab an az aY n", .expected_captures = &[_]?[]const u8{ "aY " }, .file = "built-ins/RegExp/S15.10.2.13_A2_T3.js" },
    .{ .kind = .exec_array, .pattern = "a[^]", .flags = "", .input = "   a\t\n", .expected_captures = &[_]?[]const u8{ "a\t" }, .file = "built-ins/RegExp/S15.10.2.13_A2_T2.js" },
    .{ .kind = .exec_array, .pattern = "[^]a", .flags = "m", .input = "a\naba", .expected_captures = &[_]?[]const u8{ "\na" }, .file = "built-ins/RegExp/S15.10.2.13_A2_T1.js" },
    .{ .kind = .exec_array, .pattern = "[1234567].{2}", .flags = "", .input = "abc6defghijkl", .expected_captures = &[_]?[]const u8{ "6de" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T9.js" },
    .{ .kind = .exec_array, .pattern = "[d-h]+", .flags = "", .input = "abcdefghijkl", .expected_captures = &[_]?[]const u8{ "defgh" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T8.js" },
    .{ .kind = .exec_array, .pattern = "ab[ercst]de", .flags = "", .input = "abcde", .expected_captures = &[_]?[]const u8{ "abcde" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T6.js" },
    .{ .kind = .exec_array, .pattern = "q[ax-zb](?=\\s+)", .flags = "", .input = "tqa\t  qy ", .expected_captures = &[_]?[]const u8{ "qa" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T5.js" },
    .{ .kind = .exec_array, .pattern = "q[ax-zb](?=\\s+)", .flags = "", .input = "tqaqy ", .expected_captures = &[_]?[]const u8{ "qy" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T4.js" },
    .{ .kind = .exec_array, .pattern = "q[ax-zb](?=\\s+)", .flags = "", .input = "qYqy ", .expected_captures = &[_]?[]const u8{ "qy" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T3.js" },
    .{ .kind = .exec_array, .pattern = "[\\d][\\n][^\\d]", .flags = "", .input = "line1\nline2", .expected_captures = &[_]?[]const u8{ "1\nl" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T15.js" },
    .{ .kind = .exec_array, .pattern = "[*&$]{3}", .flags = "", .input = "123*&$abc", .expected_captures = &[_]?[]const u8{ "*&$" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T14.js" },
    .{ .kind = .exec_array, .pattern = "[a-z][^1-9][a-z]", .flags = "", .input = "a1b  b2c  c3d  def  f4g", .expected_captures = &[_]?[]const u8{ "def" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T13.js" },
    .{ .kind = .exec_array, .pattern = "a[b]c", .flags = "", .input = "abc", .expected_captures = &[_]?[]const u8{ "abc" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T12.js" },
    .{ .kind = .exec_array, .pattern = "ab[.]?c", .flags = "", .input = "abc", .expected_captures = &[_]?[]const u8{ "abc" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T11.js" },
    .{ .kind = .exec_array, .pattern = "[a-c\\d]+", .flags = "", .input = "\n\nabc324234\n", .expected_captures = &[_]?[]const u8{ "abc324234" }, .file = "built-ins/RegExp/S15.10.2.13_A1_T10.js" },
    .{ .kind = .exec_array, .pattern = "1|12", .flags = "", .input = "123", .expected_captures = &[_]?[]const u8{ "1" }, .file = "built-ins/RegExp/prototype/exec/S15.10.6.2_A1_T1.js" },
};
