//! Generated by scripts/gen_unicode_tables.py from CaseFolding.txt -- do not
//! edit by hand, regenerate instead (scripts/README.md).

/// The code points outside ASCII whose simple case folding class (`u`)
/// holds an ASCII word character: what ECMA-262's WordCharacters adds
/// under `u`/`v` + `i`. Sorted.
pub const extra: []const u32 = &.{ 0x17F, 0x212A };
